### Site info:
title: 可里胡的九里巷
tagline: 不念过去, 不惧将来
author: Marco Hu
email: hzg139@163.com
description: "关注汽车后市场、O2O、移动互联网技术与产品、户外、文艺." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "可里胡, Jekyll"
#baseurl: "/blog" # the subpath of your site, e.g. /blog
#url: "http://yulijia.net/freshman21" # the base hostname & protocol for your site
locale: zh_CN

### Personal info and site tools info:
#twitter_username: yulijia
github_username:  hzg139
#disqus_shortname: hzg139
favicon:     "/images/favicon.ico"
aboutme: Hi, 我是可里胡，供职于某互联网公司，汽车后市场电商产品与技术研发负责人。双城记：工作@广州，生活@东莞。 # these are shown on aboutme-sidebar.
aboutme_photo: http://pic.yupoo.com/hzg139/EyLlhXgI/small.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "关注"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Freshman21
      href: http://yulijia.net/freshman21
      title: Another Jekyll blog theme
    - name: author's website
      href: http://yulijia.net/
      title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
